name = "caesar"
main = "functions/api/worker.js"
compatibility_date = "2025-12-08"
compatibility_flags = ["nodejs_compat"]

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "meum-diarium"
database_id = "0cf71203-f07c-46b2-8f52-765929a25d24"

[[d1_databases]]
binding = "vocab"
database_name = "vocab"
database_id = "6743a774-21c1-4c0c-a17a-086eae15d3f5"

# Environment variables
[vars]
ENVIRONMENT = "production"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
