name = "meum-diarium"  # Dein Pages-Projektname
main = "dist/index.js"
compatibility_date = "2025-12-08"

[[d1_databases]]
binding = "DB"
database_name = "meum-diarium"
database_id = "0cf71203-f07c-46b2-8f52-765929a25d24"
migrations_dir = "drizzle"
